name: Build & Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          tags: true

      - uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_RELEASE }}

      - name: Set version
        id: version
        run: |
          git fetch --tags
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build & Push Brute Force
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/jadamsx/containerised-tsp/brute-force:$VERSION -t ghcr.io/jadamsx/containerised-tsp/brute-force:latest --push backend/multi-container/brute-force

      - name: Build & Push Three-Opt
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/jadamsx/containerised-tsp/three-opt:$VERSION -t ghcr.io/jadamsx/containerised-tsp/three-opt:latest --push backend/multi-container/three-opt

      - name: Build & Push Dynamic Programming
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/jadamsx/containerised-tsp/dynamic-programming:$VERSION -t ghcr.io/jadamsx/containerised-tsp/dynamic-programming:latest --push backend/single-container/dynamic-programming

      - name: Build & Push Cheapest Insertion
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/jadamsx/containerised-tsp/cheapest-insertion:$VERSION -t ghcr.io/jadamsx/containerised-tsp/cheapest-insertion:latest --push backend/single-container/cheapest-insertion

      - name: Build & Push Nearest Neighbour
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/jadamsx/containerised-tsp/nearest-neighbour:$VERSION -t ghcr.io/jadamsx/containerised-tsp/nearest-neighbour:latest --push backend/single-container/nearest-neighbour

      - name: Build & Push Frontend Web App
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/jadamsx/containerised-tsp/web-app:$VERSION -t ghcr.io/jadamsx/containerised-tsp/web-app:latest --push frontend/web-app
