name: Build & Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build & Push Brute Force
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}/brute-force:$VERSION -t ghcr.io/${{ github.repository }}/brute-force:latest --push backend/multi-container/brute-force

      - name: Build & Push Three-Opt
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}/three-opt:$VERSION -t ghcr.io/${{ github.repository }}/three-opt:latest --push backend/multi-container/three-opt

      - name: Build & Push Dynamic Programming
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}/dynamic-programming:$VERSION -t ghcr.io/${{ github.repository }}/dynamic-programming:latest --push backend/single-container/dynamic-programming

      - name: Build & Push Cheapest Insertion
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}/cheapest-insertion:$VERSION -t ghcr.io/${{ github.repository }}/cheapest-insertion:latest --push backend/single-container/cheapest-insertion

      - name: Build & Push Nearest Neighbour
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}/nearest-neighbour:$VERSION -t ghcr.io/${{ github.repository }}/nearest-neighbour:latest --push backend/single-container/nearest-neighbour
